# Generated by Django 4.1.1 on 2023-05-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_of_user", "0021_post_post_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_case",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="post_location",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
    ]
