# Generated by Django 4.1.1 on 2023-05-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_of_user", "0023_post_post_predict"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="post_case",),
        migrations.RemoveField(model_name="post", name="post_location",),
        migrations.DeleteModel(name="Replie",),
    ]
